<a href="https://colab.research.google.com/github/Tina-Gh/PyTorch/blob/main/PytorchDocumentation/pytorch_01_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Intro suff:

In [ ]:
import torch

In [ ]:
z = torch.zeros(5, 3)
print(z)
print(z.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])


In [ ]:
i = torch.ones((5, 3), dtype=torch.int16)
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


In [ ]:
torch.manual_seed(1899)
r1 = torch.rand(2, 2)
print('r1 is: ')
print(r1)


r2 = torch.rand(2, 2)
print('r2 is: ')
print(r2)


torch.manual_seed(1899)
r3 = torch.rand(2, 2)
print('r3 is: ')
print(r3)

r1 is: 
tensor([[0.1631, 0.4325],
        [0.4405, 0.5859]])
r2 is: 
tensor([[0.2496, 0.5482],
        [0.9774, 0.2282]])
r3 is: 
tensor([[0.1631, 0.4325],
        [0.4405, 0.5859]])


In [ ]:
r = (torch.rand(2, 2) - 0.5) * 2 #is between (-1, 1)
print('r is: ')
print(r)

r is: 
tensor([[-0.5008,  0.0963],
        [ 0.9548, -0.5437]])


In [ ]:
print('|r|: ')
print(torch.abs(r))

print('\narcsin(r): ')
print(torch.asin(r))

print('\ndeterminant of r: ')
print(torch.det(r))

print('\nsvd(r): ')
print(torch.svd(r))

print('\nmean of r: ')
print(torch.std_mean(r))

print('\nmaximum of r: ')
print(torch.max(r))

|r|: 
tensor([[0.5008, 0.0963],
        [0.9548, 0.5437]])

arcsin(r): 
tensor([[-0.5245,  0.0965],
        [ 1.2689, -0.5748]])

determinant of r: 
tensor(0.1803)

svd(r): 
torch.return_types.svd(
U=tensor([[-0.4087,  0.9127],
        [ 0.9127,  0.4087]]),
S=tensor([1.2020, 0.1500]),
V=tensor([[ 0.8952, -0.4456],
        [-0.4456, -0.8952]]))

mean of r: 
(tensor(0.6993), tensor(0.0017))

maximum of r: 
tensor(0.9548)


In [ ]:
x = torch.randn(1, 10)
prev_h = torch.randn(1, 20)
w_h = torch.randn(20, 20)
w_x = torch.randn(20, 10)

i2h = torch.mm(w_x, x.t())
h2h = torch.mm(w_h, prev_h.t())

next_h = i2h + h2h
next_h = next_h.tanh()

loss = next_h.sum()
loss.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

# 2. NN model example:

In [ ]:
import torch # for all things pytorch
import torch.nn as nn # for torch.nn.Module, the parent object for pytorch models
import torch.nn.functional as F # for teh activation function

In [ ]:
class LeNet(nn.Module):

  def __init__(self):
    super(LeNet, self).__init__() #or less redundant as: super().__init__()
    self.conv1 = nn.Conv2d(1, 6, 3) #tensor(#input_channels, #output_channels, #convolution_kernel)
    self.conv2 = nn.Conv2d(6, 16, 3)
    self.fc1 = nn.Linear(16*6*6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x): #x is input
    x = F.max_pool2d(F.relu(self.conv1(x)), 2) #maxpooling over a 2*2 window #for maxpoolng window, 2 is actually (2, 2) which we can also write instead.
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    x = x.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  def num_flat_features(self, x): #could have been done literally instead in above: x.size()[1]*x.size()[2]
    size_x = x.size()[1:] #all dimensions except the batch dimension
    num_features = 1

    for s in size_x:
      num_features *= s
    return num_features

In [ ]:
net = LeNet()
print(net)

input = torch.rand(1, 1, 32, 32) #example image of size 32*32 and black & white
print('\nimage: ')
print(input)
print('\nimage shape: ')
print(input.shape)

output = net(input) #we don't call forward directly
print('\nraw output:')
print(output)
print('\nraw output shape: ')
print(output.shape)


LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

image: 
tensor([[[[0.7995, 0.3001, 0.2443,  ..., 0.3732, 0.3692, 0.9898],
          [0.2174, 0.3696, 0.3510,  ..., 0.5153, 0.5295, 0.2001],
          [0.5032, 0.8733, 0.4496,  ..., 0.3689, 0.7717, 0.0253],
          ...,
          [0.6915, 0.1036, 0.6693,  ..., 0.0758, 0.5914, 0.5840],
          [0.2117, 0.1828, 0.4010,  ..., 0.7058, 0.0770, 0.4822],
          [0.7201, 0.0173, 0.0995,  ..., 0.8576, 0.0402, 0.9390]]]])

image shape: 
torch.Size([1, 1, 32, 32])

raw output:
tensor([[-0.0170,  0.0489,  0.0940, -0.1064, -0.0564,  0.0344, -0.0090,  0.0540,
         -0.1037, -0.0420]], grad_fn=<AddmmBackward0>)

raw output shape: 
torch.Size([1, 10])


# 3. Datasets and Dataloaders:

In [ ]:
%matplotlib inline

import torch
import torchvision
import torchvision.transforms as transforms

In [ ]:
#transforming images to pytorch tensors

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

In [ ]:
#dataset:

trainset = torchvision.datasets.CIFAR10('./data', train=True, download=True, transform=transform)

100%|██████████| 170498071/170498071 [00:18<00:00, 9227919.27it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data


In [ ]:
#data loader:

trainloader = torch.utils.data.DataLoader(trainset, batch_size=4, shuffle=True, num_workers=2)

In [ ]:
# #show a sample of teh image:

# import matplotlib.pyplot as plt
# import numpy as np

# classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

# def imshow(img):
#   img = img/2 + 0.5 #unnormalize
#   npimg = img.numpy()
#   plt.imshow(np.transpose(npimg, (1, 2, 0)))

# #get some random training images
# dataiter = iter(trainloader)
# images, labels = dataiter.next()

# #show images
# imshow(torchvision.utils.make_grid(images))
# #print labels
# print(''.join('%5s' % classes[labels[j]] for j in range(4)))

# 4. Training the model:

In [ ]:
#Find it under 'pytorch_02.ipynb'