<a href="https://colab.research.google.com/github/Tina-Gh/PyTorch/blob/main/PytorchDocumentation/pytorch_03_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## More manipulations of tensors:


In [ ]:
import torch
import math

## creating some random tensors:

In [ ]:
#creating tensors:

x = torch.empty(3, 4)
print(x)
print(type(x))

tensor([[ 3.3631e-44,  1.7751e+28, -6.6409e+14,  4.4416e-41],
        [ 2.8026e-45,  2.0706e-19,  1.1723e-19,  1.3563e-19],
        [ 5.6052e-45,  0.0000e+00,  5.6052e-45,  7.0065e-45]])
<class 'torch.Tensor'>


In [ ]:
#method 1: (using torch factory defined tensors)

a = torch.randn(3, 4)
print('randn tensor:\n ', a)

torch.manual_seed(8888)
b = torch.rand(3, 4)
print('rand tensor:\n ', b)

c = torch.zeros(3, 4)
print('zeros tensor:\n ', c)

d =torch.ones(3, 4)
print('ones tesor:\n ', d)

randn tensor:
  tensor([[ 1.1730, -0.1184, -0.8332, -0.9962],
        [-0.4634,  0.2259,  0.7540, -1.4356],
        [ 1.6856, -0.0467, -0.5652, -1.0751]])
rand tensor:
  tensor([[0.3704, 0.9766, 0.7204, 0.8029],
        [0.2201, 0.5525, 0.2689, 0.8670],
        [0.0968, 0.9046, 0.2735, 0.3837]])
zeros tensor:
  tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones tesor:
  tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#method 2: (using torch.*_like())

x = torch.empty(2, 2, 3)
print(x)
print(x.shape)

empty_like_x = torch.empty_like(x)
print('\n', empty_like_x)
print(empty_like_x.shape)

zeros_like_x = torch.zeros_like(x)
print('\n', zeros_like_x)
print(zeros_like_x.shape)

ones_like_x = torch.ones_like(x)
print('\n', ones_like_x)
print(ones_like_x.shape)

rand_like_x = torch.rand_like(x)
print('\n', rand_like_x)
print(rand_like_x.shape)

tensor([[[ 0.0000e+00,  0.0000e+00, -1.1271e+29],
         [ 3.1866e-41, -1.7126e+28,  3.1866e-41]],

        [[-1.1106e-26,  4.4416e-41,  1.4013e-45],
         [ 0.0000e+00,  1.6816e-44,  0.0000e+00]]])
torch.Size([2, 2, 3])

 tensor([[[ 1.4013e-45,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 1.5835e-43,  0.0000e+00, -1.1288e+29],
         [ 3.1866e-41, -1.0448e+15,  4.4416e-41]]])
torch.Size([2, 2, 3])

 tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])

 tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])

 tensor([[[0.9538, 0.9426, 0.9787],
         [0.8919, 0.5594, 0.8498]],

        [[0.4982, 0.1720, 0.9360],
         [0.2075, 0.8987, 0.0079]]])
torch.Size([2, 2, 3])


In [ ]:
#method 3: (using torch.tensor(()) or torch.tensor([]))

# some_constants = torch.tensor()

some_integers = torch.tensor((1, 2, 3, 4, 5, 6, 7, 8, 9))
print('\n', some_integers)
print(some_integers.shape)

more_integers = torch.tensor(((2, 4, 6), (3, 6, 9))) #or using [] instead of() for each element.
print('\n', more_integers)
print(more_integers.shape)


 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9])

 tensor([[2, 4, 6],
        [3, 6, 9]])
torch.Size([2, 3])


## Tensor data types:

In [ ]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 8.5091, 11.5893,  2.3249],
        [19.4933, 18.2966, 10.3135]], dtype=torch.float64)
tensor([[ 8, 11,  2],
        [19, 18, 10]], dtype=torch.int32)


## Broadcasting:

In [ ]:
#using *
# even multiplying tensors of different shapes

## in-place arithmatic function:

In [ ]:
#adding '_' to arithmatic operations make it so that the original variable is updated in the sam eexisting allocated memory space,
#instead of allocating new space in memory to the new variable.
#example:

a = torch.ones(2, 3)
b = torch.ones(2, 3)

print(a)
print(a.add(b))
print(a)

print('\n')
print(a)
print(a.add_(b))
print(a) #as can be see, the value of a is updated in the same memory space.

#you can also achieve a similar thing using parameter 'out' in the arithmatic function.

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


## Copying tensors:

In [ ]:
# the same copy with the original changing: a = b
# but a cloned copy that doesn't change teh original: b = a.clone()


In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a
print(torch.eq(a, b))

a[0][1] = 561
print(b)

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
#Autograd
#requires_grad = True
#detach().clone()

a = torch.rand(2, 2, requires_grad=True)
b = a.clone()
c = a.detach.clone()

## Moving to GPU:

In [ ]:
#hardware requirement: GPU and teh drivers should already be set up.

In [ ]:
if torch.cuda.is_available():
  print('We have a GPU.')
else:
  print('No GPUs found.')

We have a GPU.


In [ ]:
#then, we should move the data to memory accessible by the GPU:

if torch.cuda.is_available():
  gpu_rand = torch.rand(2, 2, device='cuda')
  print(gpu_rand)
else:
  print('No GPUs.')

tensor([[0.4019, 0.3625],
        [0.2853, 0.2299]], device='cuda:0')


In [ ]:
#querying teh number of available GPUs: torch.cuda.device_count()

torch.cuda.device_count()

1

In [ ]:
if torch.cuda.is_available():
  my_device = torch.device('cuda')
else:
  my_device = torch.device('cpu')
print('Device: {}' .format(my_device))

a = torch.rand(2, 2, device=my_device)
print(a)

Device: cuda
tensor([[0.4061, 0.4324],
        [0.4927, 0.7431]], device='cuda:0')


In [ ]:
#to move an existing tensor from CPU to GPU:

y = torch.rand(2, 2) #in CPU
#the same as: y = torch.rand(2, 2, device='cpu') or device='cuda'
print(y)

y = y.to(device=my_device) #in GPU
print('\n', y)

tensor([[0.8375, 0.2433],
        [0.1439, 0.7195]], device='cuda:0')

 tensor([[0.8375, 0.2433],
        [0.1439, 0.7195]], device='cuda:0')


## changing the tensor dimensions:

In [ ]:
#unsqeeze(0) =  adds a dimension 1 at the begging (could be used for batch making for feeding into the model OR used for broadcasting)

#squeeze(0) =  removes teh first dimension if it's 1.

## Numpy bridge:



In [ ]:
# yet, they will still use the same space in the memory.

import numpy as np

a_array = np.ones((2, 3))
print(a_array)

a_tensor = torch.from_numpy(a_array)
print('\n', a_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]

 tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
b_tensor = torch.rand(2, 3)
print(b_tensor)

b_array = b_tensor.numpy()
print('\n', b_array)

tensor([[0.7776, 0.8834, 0.7304],
        [0.9187, 0.4427, 0.7559]])

 [[0.7775574  0.8834339  0.7304397 ]
 [0.9186924  0.44273615 0.75591505]]
